///creep_weapon_data();

    return json_decode(
    '{
        "unarmed" : {
            "itemtype" : -1,
            "th_plus"     : 0,
            "th_rolls"    : 0,
            "d_plus"        : 1,
            "d_rolls"     : 1,
            "d_sides"      : 4,
            "spread" : 0,
            "splash"        : 0,
            "radius"        : 0,
            "atkspd" : 120,
            "atkspd2" : 20,
            "range"  : 32,
            "crit"   : 1,
            "multiplier"   : 2,
            "swarm"  : 1,
            "shots"   : 1,
            "charges"   : 0,
            "penetration"   : 1,
            "s_factor"   : 1,
            "knock"  : 1,
            "suppr"     : 0,
            "shock"     : 0,
            "lifesteal" : 0,
            "melee"  : true,
            "sound"  : 6,
            "type"   : 0,
            "sklt"   : 0,
            "wspr"   : 0,
        },
        
        "sword" : {
            "itemtype" : -1,
            "th_plus"     : 0,
            "th_rolls"    : 0,
            "d_plus"        : 1,
            "d_rolls"     : 1,
            "d_sides"      : 4,
            "spread" : 0,
            "splash"        : 0,
            "radius"        : 0,
            "atkspd" : 120,
            "atkspd2" : 20,
            "range"  : 32,
            "crit"   : 1,
            "multiplier"   : 2,
            "swarm"  : 1,
            "shots"   : 1,
            "charges"   : 0,
            "penetration"   : 1,
            "s_factor"   : 1,
            "knock"  : 1,
            "suppr"     : 0,
            "shock"     : 0,
            "lifesteal" : 0,
            "melee"  : true,
            "sound"  : 6,
            "type"   : 0,
            "sklt"   : 0,
            "wspr"   : 3,
        },
        
        "gun" : {
            "itemtype" : -1,
            "th_plus"     : 0,
            "th_rolls"    : 0,
            "d_plus"        : 2,
            "d_rolls"     : 1,
            "d_sides"      : 4,
            "spread" : 6.5,
            "splash"        : 0,
            "radius"        : 15,
            "atkspd" : 100,
            "atkspd2" : 15,
            "range"  : 120,
            "crit"   : 1,
            "multiplier"   : 2,
            "swarm"  : 1,
            "shots"   : 1,
            "charges"   : 0,
            "penetration"   : 1,
            "s_factor"   : 1,
            "knock"  : 0.35,
            "suppr"     : 0,
            "shock"     : 0,
            "lifesteal" : 0,
            "melee"  : false,
            "sound"  : 0,
            "type"   : 1,
            "sklt"   : 1,
            "wspr"   : 1,  
        },
        
        "tower" : {
            "itemtype" : -1,
            "th_plus"     : 1,
            "th_rolls"    : 1,
            "d_plus"        : 2,
            "d_rolls"     : 1,
            "d_sides"      : 6,
            "spread" : 5,
            "splash"        : 0,
            "radius"        : 16,
            "atkspd" : 120,
            "atkspd2" : 20,
            "range"  : 160,
            "crit"   : 3,
            "multiplier"   : 2.5,
            "swarm"  : 1,
            "shots"   : 3,
            "charges"   : 0,
            "penetration"   : 1,
            "s_factor"   : 1,
            "knock"  : 1.1,
            "suppr"     : 0,
            "shock"     : 0,
            "lifesteal" : 0,
            "melee"  : false,
            "sound"  : 2,
            "type"   : 1,
            "sklt"   : 1,
            "wspr"   : 3,
        }
    }');
